#!/usr/bin/perl

##
# SPD2Shape (v1.0.0a)
# Epigenetics Unit @ HuGeF [Human Genetics Foundation]
#
# Author:  Danny Incarnato (danny.incarnato[at]hugef-torino.org)
# Summary: Generates RNAstructure's SHAPE constraint files from SPD files
#
# This program is free software, and can be redistribute  and/or modified
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# Please see <http://www.gnu.org/licenses/> for more informations.
##

use strict;
use FindBin qw($Bin);
use Getopt::Long qw(:config no_ignore_case);
use XML::Simple;

use lib $Bin . "/lib";

use Core::Mathematics;

my ($spd, $help, $i, @reactivity);
$i = 0;

do {
    
    local $SIG{__WARN__} = sub { };

    GetOptions( "h|help" => \$help ) or help(1);

};

help() if ($help);

die "\n  [!] Error: No SPD file has been specified\n\n" unless($ARGV[0]);
die "\n  [!] Error: Specified SPD file doesn't exist\n\n" unless(-e $ARGV[0]);

eval { $spd = XMLin($ARGV[0]); };

if ($@) { die "\n  [!] Error: Unable to read from input SPD file (" . $@ . ")\n\n"; }

$spd->{transcript}->{reactivity} =~ s/\s+?//g;
@reactivity = split(/,/, $spd->{transcript}->{reactivity});

for (@reactivity) {
    
    $i++;
    
    next if (isnan($_));
    
    print $i . " " . $_ . "\n";
    
}

sub help {
    
    print "\n  [!] Error: Invalid option. Please check the help\n" if ($_[0]);
    
    die <<HELP;
 
 SPD2Shape (v1.0.0a)
 Epigenetics Units @ HuGeF [Human Genetics Foundation]
 Group leader: Prof. Salvatore Oliviero
    
 Author:  Danny Incarnato (danny.incarnato[at]hugef-torino.org)
 Summary: Generates RNAstructure's SHAPE constraint files from SPD files
 
 Usage:   spd2shape <SPD file> > output.shape
 
HELP

}